# Generated by Django 5.2.14 on 2026-05-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laser_type', models.CharField(choices=[('uv', 'УФ лазер'), ('co2', 'CO₂ лазер'), ('fiber', 'Файбер лазер')], max_length=10, unique=True, verbose_name='Тип лазера')),
                ('title', models.CharField(max_length=160, verbose_name='Назва')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lasers/', verbose_name='Зображення')),
                ('applications', models.TextField(blank=True, verbose_name='Сфери застосування (кожна з нового рядка)')),
                ('power_range', models.CharField(blank=True, max_length=80, verbose_name='Діапазон потужності')),
                ('wavelength', models.CharField(blank=True, max_length=80, verbose_name='Довжина хвилі')),
                ('marking_speed', models.CharField(blank=True, max_length=80, verbose_name='Швидкість маркування')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Лазерний маркіратор',
                'verbose_name_plural': 'Лазерні маркіратори',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='QualityProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('metal_detector', 'Металодетектор'), ('xray', 'Рентгенівський інспектор'), ('checkweigher', 'Чеквейер'), ('filling', 'Система контролю розливу')], max_length=20, verbose_name='Категорія')),
                ('title', models.CharField(max_length=160, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quality/', verbose_name='Зображення')),
                ('features', models.TextField(blank=True, verbose_name='Переваги (кожна з нового рядка)')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Обладнання контролю якості',
                'verbose_name_plural': 'Обладнання контролю якості',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ФортунаПринт', max_length=120, verbose_name='Назва компанії')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Слоган')),
                ('phone_1', models.CharField(blank=True, max_length=30, verbose_name='Телефон 1')),
                ('phone_2', models.CharField(blank=True, max_length=30, verbose_name='Телефон 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='Hero заголовок')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='Hero підзаголовок')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta description (головна)')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
            },
        ),
    ]
