# Generated by Django 5.2.14 on 2026-05-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(blank=True, default='Ми раді відповісти на ваші запитання та допомогти підібрати обладнання для вашого виробництва.', verbose_name='Вступний текст')),
                ('page_title', models.CharField(blank=True, default='Контакти | ФортунаПринт', max_length=160, verbose_name='SEO — title')),
                ('meta_description', models.CharField(blank=True, default='Зв’яжіться з ФортунаПринт: Київ, Вишняківська 13а/49.', max_length=300, verbose_name='SEO — meta description')),
            ],
            options={
                'verbose_name': 'Сторінка «Контакти»',
            },
        ),
        migrations.CreateModel(
            name='LabelingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('applicator', 'Аплікатор'), ('print_apply', 'Принтер-аплікатор'), ('thermal', 'Термотрансферний принтер'), ('other', 'Інше')], default='other', max_length=20, verbose_name='Категорія')),
                ('title', models.CharField(max_length=160, verbose_name='Назва')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='labeling/', verbose_name='Зображення')),
                ('features', models.TextField(blank=True, verbose_name='Характеристики (кожна з нового рядка)')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Обладнання для етикетування',
                'verbose_name_plural': 'Обладнання для етикетування',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='MarkingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_direction_label', models.CharField(blank=True, default='Напрям 01', max_length=30, verbose_name='Hero — мітка напряму')),
                ('hero_title', models.CharField(blank=True, default='Маркування', max_length=200, verbose_name='Hero — заголовок')),
                ('hero_subtitle', models.TextField(blank=True, default='Лазерне нанесення штрих-кодів, QR-кодів, серійних номерів, логотипів та дат виробництва на будь-яких матеріалах — метал, пластик, скло, дерево, шкіра.', verbose_name='Hero — підзаголовок')),
                ('intro_title', models.CharField(blank=True, default='Чому лазерне маркування?', max_length=200, verbose_name='Intro — заголовок')),
                ('intro_body_1', models.TextField(blank=True, default='Лазерне маркування є незамінним на сучасному виробництві — воно забезпечує стійке, нестираємо маркування без використання хімікатів та витратних матеріалів.', verbose_name='Intro — абзац 1')),
                ('intro_body_2', models.TextField(blank=True, default='Ми постачаємо китайські лазерні маркіратори трьох типів: ультрафіолетові (УФ), CO₂ та файбер (волоконні). Кожен тип оптимізовано для конкретних матеріалів та задач.', verbose_name='Intro — абзац 2')),
                ('cta_title', models.CharField(blank=True, default='Підберемо лазерний маркіратор для вашого виробництва', max_length=200, verbose_name='CTA — заголовок')),
                ('cta_body', models.TextField(blank=True, default='Вкажіть матеріал, швидкість лінії та тип маркування — ми запропонуємо оптимальне рішення.', verbose_name='CTA — текст')),
                ('page_title', models.CharField(blank=True, default='Маркування — Лазерні маркіратори | ФортунаПринт', max_length=160, verbose_name='SEO — title')),
                ('meta_description', models.CharField(blank=True, default='Лазерні маркіратори для промислового застосування: УФ, CO₂, файбер лазери.', max_length=300, verbose_name='SEO — meta description')),
            ],
            options={
                'verbose_name': 'Сторінка «Маркування»',
            },
        ),
        migrations.CreateModel(
            name='QualityCategoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('metal_detector', 'Металодетектори'), ('xray', 'Рентгенівські інспектори'), ('checkweigher', 'Чеквейери'), ('filling', 'Системи контролю розливу')], max_length=20, unique=True, verbose_name='Категорія')),
                ('section_number', models.CharField(blank=True, help_text='Наприклад: 01', max_length=10, verbose_name='Номер секції')),
                ('section_title', models.CharField(max_length=160, verbose_name='Заголовок секції')),
                ('body_primary', models.TextField(verbose_name='Основний текст')),
                ('body_secondary', models.TextField(blank=True, verbose_name='Додатковий текст')),
                ('features_label', models.CharField(blank=True, help_text='Наприклад: «Переваги металодетекторів»', max_length=160, verbose_name='Заголовок переваг')),
                ('features', models.TextField(blank=True, verbose_name='Переваги (кожна з нового рядка)')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Секція категорії КЯ',
                'verbose_name_plural': 'Секції категорій КЯ',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='QualityControlPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_direction_label', models.CharField(blank=True, default='Напрям 02', max_length=30, verbose_name='Hero — мітка напряму')),
                ('hero_title', models.CharField(blank=True, default='Системи контролю якості', max_length=200, verbose_name='Hero — заголовок')),
                ('hero_subtitle', models.TextField(blank=True, default='Комплексні рішення для інспекції продукції на виробничій лінії. Металодетектори, рентгенівські інспектори, чеквейери та системи контролю розливу — все для виконання вимог HACCP.', verbose_name='Hero — підзаголовок')),
                ('haccp_intro_title', models.CharField(blank=True, default='Контроль якості для виконання HACCP', max_length=200, verbose_name='HACCP — заголовок')),
                ('haccp_body_1', models.TextField(blank=True, default='Кожен виробник продукції стикається з необхідністю встановлення інспекційного обладнання як ККТ (Критичної Контрольної Точки) для виконання плану HACCP.', verbose_name='HACCP — абзац 1')),
                ('haccp_body_2', models.TextField(blank=True, default='Системи інспекції виробництва T-LINE Technology Co., Ltd забезпечують контроль рівня наливу, укупорки, етикетування, маркування та цілісності тари. При виявленні відхилень — автоматичне відбракування пневматичним пушером.', verbose_name='HACCP — абзац 2')),
                ('cta_title', models.CharField(blank=True, default='Підберемо систему контролю якості під ваш HACCP-план', max_length=200, verbose_name='CTA — заголовок')),
                ('cta_body', models.TextField(blank=True, default='Опишіть вашу виробничу лінію — ми запропонуємо відповідне рішення.', verbose_name='CTA — текст')),
                ('page_title', models.CharField(blank=True, default='Системи контролю якості | ФортунаПринт', max_length=160, verbose_name='SEO — title')),
                ('meta_description', models.CharField(blank=True, default='Обладнання для контролю якості: металодетектори, рентгенівські інспектори, чеквейери, системи контролю розливу. HACCP.', max_length=300, verbose_name='SEO — meta description')),
            ],
            options={
                'verbose_name': 'Сторінка «Контроль якості»',
            },
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Наприклад: 3, HACCP, 24/7', max_length=30, verbose_name='Значення')),
                ('label', models.CharField(max_length=100, verbose_name='Підпис')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Статистичний показник',
                'verbose_name_plural': 'Статистичні показники',
                'ordering': ['ordering'],
            },
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='meta_description',
        ),
        migrations.CreateModel(
            name='LabelingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_direction_label', models.CharField(blank=True, default='Напрям 03', max_length=30, verbose_name='Hero — мітка напряму')),
                ('hero_title', models.CharField(blank=True, default='Етикетування', max_length=200, verbose_name='Hero — заголовок')),
                ('hero_subtitle', models.TextField(blank=True, default='Автоматичні та напівавтоматичні системи нанесення етикеток для виробничих ліній. Рішення для будь-яких типів тари та форм упаковки.', verbose_name='Hero — підзаголовок')),
                ('cta_title', models.CharField(blank=True, default='Залиште заявку на підбір обладнання для етикетування', max_length=200, verbose_name='CTA — заголовок')),
                ('cta_body', models.TextField(blank=True, default='Ми зв’яжемось з вами та надамо повну інформацію.', verbose_name='CTA — текст')),
                ('page_title', models.CharField(blank=True, default='Етикетування — Обладнання для нанесення етикеток | ФортунаПринт', max_length=160, verbose_name='SEO — title')),
                ('meta_description', models.CharField(blank=True, default='Промислове обладнання для нанесення етикеток. Автоматичні та напівавтоматичні аплікатори для виробничих ліній.', max_length=300, verbose_name='SEO — meta description')),
                ('products', models.ManyToManyField(blank=True, to='content.labelingproduct', verbose_name='Обладнання')),
            ],
            options={
                'verbose_name': 'Сторінка «Етикетування»',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, default='Промислове обладнання для маркування, контролю та етикетування', max_length=200, verbose_name='Hero — заголовок')),
                ('hero_subtitle', models.TextField(blank=True, default='Постачання та впровадження обладнання для виробничих ліній — від лазерного маркування до систем контролю якості HACCP.', verbose_name='Hero — підзаголовок')),
                ('directions_section_title', models.CharField(blank=True, default='Три напрями — одна компанія', max_length=200, verbose_name='Напрями — заголовок розділу')),
                ('about_title', models.TextField(blank=True, default='ТОВ «ФортунаПринт» — ваш партнер у сфері маркування та контролю якості', verbose_name='Про нас — заголовок')),
                ('about_body_1', models.TextField(blank=True, default='Ми постачаємо та впроваджуємо промислове обладнання для виробничих підприємств харчової, фармацевтичної та косметичної галузей.', verbose_name='Про нас — абзац 1')),
                ('about_body_2', models.TextField(blank=True, default='Наші рішення відповідають вимогам HACCP та міжнародним стандартам якості. Від підбору обладнання до технічного обслуговування — ми супроводжуємо клієнта на кожному етапі.', verbose_name='Про нас — абзац 2')),
                ('cta_title', models.CharField(blank=True, default='Підберемо обладнання під ваші задачі', max_length=200, verbose_name='CTA — заголовок')),
                ('cta_body', models.TextField(blank=True, default='Залиште заявку — наш спеціаліст зв’яжеться з вами та запропонує оптимальне рішення.', verbose_name='CTA — текст')),
                ('page_title', models.CharField(blank=True, default='ФортунаПринт — Маркування, Контроль якості, Етикетування', max_length=160, verbose_name='SEO — title')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='SEO — meta description')),
                ('stats', models.ManyToManyField(blank=True, to='content.statitem', verbose_name='Статистика')),
            ],
            options={
                'verbose_name': 'Головна сторінка',
            },
        ),
    ]
