# Generated by Django 5.2.14 on 2026-05-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_page_models_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Поштовий індекс'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='street_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Вулиця, будинок'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адреса (повна)'),
        ),
    ]
