# Generated by Django 5.2.14 on 2026-06-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_labeling_categories_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIJProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(choices=[('89xx', 'Серія 89хх'), ('99xx', 'Серія 99хх')], max_length=10, unique=True, verbose_name='Серія')),
                ('model_numbers', models.CharField(help_text='Наприклад: Linx 8900, 8920, 8940', max_length=160, verbose_name='Моделі (через кому)')),
                ('title', models.CharField(max_length=160, verbose_name='Назва')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='marking/cij/', verbose_name='Зображення')),
                ('specs', models.TextField(blank=True, help_text='Кожен рядок — окрема характеристика', verbose_name='Характеристики (кожна з нового рядка)')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Каплеструйний маркіратор',
                'verbose_name_plural': 'Каплеструйні маркіратори',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='TTOProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_series', models.CharField(help_text='Наприклад: TT500, TT750, TT1000', max_length=20, unique=True, verbose_name='Серія моделі')),
                ('variants', models.CharField(blank=True, help_text='Наприклад: Linx TT500 RH', max_length=255, verbose_name='Варіанти (через кому)')),
                ('title', models.CharField(max_length=160, verbose_name='Назва')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='marking/tto/', verbose_name='Зображення')),
                ('print_widths', models.CharField(blank=True, help_text='Наприклад: 32 мм, 53 мм', max_length=60, verbose_name='Ширина друку (мм)')),
                ('specs', models.TextField(blank=True, verbose_name='Характеристики (кожна з нового рядка)')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Термотрансферний маркіратор',
                'verbose_name_plural': 'Термотрансферні маркіратори',
                'ordering': ['ordering'],
            },
        ),
    ]
