# Generated by Django 5.2.14 on 2026-06-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_add_cij_tto_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
