# Generated by Django 5.1.15 on 2026-06-22 12:10

from django.db import migrations, models


HOME_ABOUT = {
    'about_title': (
        'ТОВ «ФортунаПринт» — команда експертів у сфері промислового маркування '
        'та етикетування з понад 25-річним досвідом роботи.'
    ),
    'about_body_1': (
        'Ми пропонуємо комплексні рішення для бізнесу: від підбору та постачання сучасного '
        'маркувального й етикетувального обладнання до впровадження систем контролю якості '
        'на виробництві. Наші технології та рішення успішно використовуються підприємствами '
        'різних галузей промисловості по всій Україні.'
    ),
    'about_body_2': (
        'Основою успіху компанії є наші фахівці. Багаторічний досвід, десятки реалізованих '
        'проєктів і глибока технічна експертиза дозволяють нам ефективно вирішувати навіть '
        'найскладніші виробничі завдання.'
    ),
    'about_body_3': (
        'Ми не обмежуємося постачанням обладнання. Наша мета — допомагати клієнтам оптимізувати '
        'виробничі процеси, підвищувати якість продукції, збільшувати продуктивність та '
        'скорочувати операційні витрати.'
    ),
    'about_body_4': (
        'Обираючи ТОВ «ФортунаПринт», ви отримуєте надійного партнера, який розуміє '
        'специфіку вашої галузі та пропонує ефективні, перевірені практикою рішення для '
        'розвитку вашого бізнесу.'
    ),
}


def update_home_about(apps, schema_editor):
    HomePage = apps.get_model('content', 'HomePage')
    StatItem = apps.get_model('content', 'StatItem')
    for home in HomePage.objects.all():
        for field, value in HOME_ABOUT.items():
            setattr(home, field, value)
        home.save(update_fields=list(HOME_ABOUT.keys()))
    StatItem.objects.filter(
        label='Років на ринку промислового обладнання',
        value='15+',
    ).update(value='25+')


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_slug_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_body_3',
            field=models.TextField(blank=True, default='Ми не обмежуємося постачанням обладнання. Наша мета — допомагати клієнтам оптимізувати виробничі процеси, підвищувати якість продукції, збільшувати продуктивність та скорочувати операційні витрати.', verbose_name='Про нас — абзац 3'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_body_4',
            field=models.TextField(blank=True, default='Обираючи ТОВ «ФортунаПринт», ви отримуєте надійного партнера, який розуміє специфіку вашої галузі та пропонує ефективні, перевірені практикою рішення для розвитку вашого бізнесу.', verbose_name='Про нас — абзац 4'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_body_1',
            field=models.TextField(blank=True, default='Ми пропонуємо комплексні рішення для бізнесу: від підбору та постачання сучасного маркувального й етикетувального обладнання до впровадження систем контролю якості на виробництві. Наші технології та рішення успішно використовуються підприємствами різних галузей промисловості по всій Україні.', verbose_name='Про нас — абзац 1'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_body_2',
            field=models.TextField(blank=True, default='Основою успіху компанії є наші фахівці. Багаторічний досвід, десятки реалізованих проєктів і глибока технічна експертиза дозволяють нам ефективно вирішувати навіть найскладніші виробничі завдання.', verbose_name='Про нас — абзац 2'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_title',
            field=models.TextField(blank=True, default='ТОВ «ФортунаПринт» — команда експертів у сфері промислового маркування та етикетування з понад 25-річним досвідом роботи.', verbose_name='Про нас — заголовок'),
        ),
        migrations.RunPython(update_home_about, migrations.RunPython.noop),
    ]
