# Generated by Django 5.1.15 on 2026-06-22 12:23

from django.db import migrations, models

DIRECTIONS_SECTION_TITLE = 'Повний спектр промислових рішень від єдиного експерта'


def update_directions_title(apps, schema_editor):
    HomePage = apps.get_model('content', 'HomePage')
    HomePage.objects.update(directions_section_title=DIRECTIONS_SECTION_TITLE)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_home_about_paragraphs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='directions_section_title',
            field=models.CharField(blank=True, default='Повний спектр промислових рішень від єдиного експерта', max_length=200, verbose_name='Напрями — заголовок розділу'),
        ),
        migrations.RunPython(update_directions_title, migrations.RunPython.noop),
    ]
