# Generated by Django 5.1.15 on 2026-06-22 13:11

from django.db import migrations, models

MARKING_HERO_SUBTITLE = (
    'Повний спектр маркувальних технологій в одних руках — це ваш надійний партнер '
    'у автоматизації виробничих процесів та ідентифікації товарів. Ми забезпечуємо '
    'бізнес усім необхідним: від підбору обладнання під ключ до постачання '
    'оригінальних витратних матеріалів і сервісу.'
)


def update_marking_hero(apps, schema_editor):
    MarkingPage = apps.get_model('content', 'MarkingPage')
    MarkingPage.objects.update(hero_subtitle=MARKING_HERO_SUBTITLE)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_directions_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markingpage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Повний спектр маркувальних технологій в одних руках — це ваш надійний партнер у автоматизації виробничих процесів та ідентифікації товарів. Ми забезпечуємо бізнес усім необхідним: від підбору обладнання під ключ до постачання оригінальних витратних матеріалів і сервісу.', verbose_name='Hero — підзаголовок'),
        ),
        migrations.RunPython(update_marking_hero, migrations.RunPython.noop),
    ]
