# Generated by Django 5.2.14 on 2026-06-23 08:28

from django.db import migrations, models


def seed_xray_gallery(apps, schema_editor):
    GalleryImage = apps.get_model('content', 'GalleryImage')
    if GalleryImage.objects.filter(gallery='xray_foodman').exists():
        return
    items = [
        ('quality/easyweigh_xray.jpg', 'Рентгенівський інспектор FOODMAN'),
        ('brands/easyweigh_product.jpg', 'FOODMAN'),
    ]
    for ordering, (path, alt) in enumerate(items):
        GalleryImage.objects.create(
            gallery='xray_foodman',
            ordering=ordering,
            alt_text=alt,
            image=path,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_qc_page_corrections'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.CharField(choices=[('xray_foodman', 'КЯ — галерея FOODMAN (рентген)')], max_length=30, verbose_name='Галерея')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Зображення')),
                ('alt_text', models.CharField(blank=True, max_length=160, verbose_name='Alt-текст')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Зображення галереї',
                'verbose_name_plural': 'Галереї — зображення',
                'ordering': ['gallery', 'ordering'],
            },
        ),
        migrations.AddField(
            model_name='laserproduct',
            name='brochure',
            field=models.FileField(blank=True, help_text='Якщо порожньо — використовується файл з /static/brochures/lasers/', null=True, upload_to='brochures/lasers/', verbose_name='PDF-брошура'),
        ),
        migrations.AddField(
            model_name='qualitycontrolpage',
            name='filling_extra_1_body',
            field=models.TextField(blank=True, default='Інспектор дозволяє визначити коректність рівня наповнення та закупорювання в скляних-, ПЕТ пляшках та алюмінієвих та жерстяних банках. Система дозволяє безконтактно визначити недолив та/або перелив, у тому числі і піниться продукту. Як опція для даної системи пропонуються:', verbose_name='Розлив — блок 1 текст'),
        ),
        migrations.AddField(
            model_name='qualitycontrolpage',
            name='filling_extra_1_features',
            field=models.TextField(blank=True, default='функція контролю наявності кришки\nфункція контролю наявності етикетки\nфункція FMS', verbose_name='Розлив — блок 1 пункти (кожен з нового рядка)'),
        ),
        migrations.AddField(
            model_name='qualitycontrolpage',
            name='filling_extra_1_title',
            field=models.CharField(blank=True, default='Рентген інспектор рівня наливу', max_length=200, verbose_name='Розлив — блок 1 заголовок'),
        ),
        migrations.AddField(
            model_name='qualitycontrolpage',
            name='filling_extra_2_body',
            field=models.TextField(blank=True, default="Система використовує зв'язок з рентгенівським випромінювачем і детектором, який на основі безконтактної технології виявлення забезпечує перевірку групової упаковки з продуктами розливу і дозволяє відбракувати групові упаковки, що не пройшли кваліфікацію.", verbose_name='Розлив — блок 2 текст'),
        ),
        migrations.AddField(
            model_name='qualitycontrolpage',
            name='filling_extra_2_title',
            field=models.CharField(blank=True, default='Інспектор групової упаковки', max_length=200, verbose_name='Розлив — блок 2 заголовок'),
        ),
        migrations.RunPython(seed_xray_gallery, migrations.RunPython.noop),
    ]
