# Generated by Django 5.2.14 on 2026-06-23 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_admin_content_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='gallery',
            field=models.CharField(blank=True, choices=[('xray_foodman', 'КЯ — галерея FOODMAN (рентген)')], max_length=30, verbose_name='Галерея'),
        ),
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('marking', 'Маркування'), ('quality', 'Контроль якості'), ('labeling', 'Етикетування')], max_length=20, verbose_name='Сторінка')),
                ('slug', models.SlugField(max_length=40, verbose_name='Slug (якір на сайті)')),
                ('section_label', models.CharField(blank=True, help_text='Наприклад: «Напрям 01 — Маркування» або «01»', max_length=80, verbose_name='Мітка розділу')),
                ('section_number', models.CharField(blank=True, max_length=10, verbose_name='Номер секції')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок розділу')),
                ('body_primary', models.TextField(blank=True, verbose_name='Основний текст')),
                ('body_secondary', models.TextField(blank=True, verbose_name='Додатковий текст')),
                ('features_label', models.CharField(blank=True, max_length=160, verbose_name='Заголовок переваг')),
                ('features', models.TextField(blank=True, verbose_name='Переваги (кожна з нового рядка)')),
                ('header_style', models.CharField(choices=[('category', 'Блок категорії (Маркування)'), ('numbered', 'Нумерований (КЯ / Етикетування)'), ('simple', 'Простий заголовок')], default='numbered', max_length=20, verbose_name='Стиль заголовка')),
                ('layout', models.CharField(choices=[('detail', 'Картки детально (фото + текст)'), ('grid', 'Сітка карток'), ('gallery', 'Галерея фото'), ('filling', 'Контроль розливу (КЯ)'), ('text', 'Лише текст (без карток)')], default='grid', max_length=20, verbose_name='Макет карток')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Розділ сторінки',
                'verbose_name_plural': 'Розділи сторінок',
                'ordering': ['page', 'ordering'],
                'constraints': [models.UniqueConstraint(fields=('page', 'slug'), name='contentsection_page_slug_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ContentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_label', models.CharField(blank=True, help_text='Наприклад: «Серія 89хх» або «УФ лазер»', max_length=80, verbose_name='Мітка картки')),
                ('title', models.CharField(max_length=160, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=80, verbose_name='Slug (якір)')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/cards/', verbose_name='Зображення')),
                ('model_tags', models.CharField(blank=True, max_length=255, verbose_name='Моделі / теги (через кому)')),
                ('variants', models.CharField(blank=True, max_length=255, verbose_name='Варіанти (через кому)')),
                ('print_widths', models.CharField(blank=True, max_length=80, verbose_name='Ширина друку')),
                ('specs', models.TextField(blank=True, verbose_name='Характеристики (кожна з нового рядка)')),
                ('features', models.TextField(blank=True, verbose_name='Переваги (кожна з нового рядка)')),
                ('wavelength', models.CharField(blank=True, max_length=80, verbose_name='Довжина хвилі')),
                ('power_range', models.CharField(blank=True, max_length=80, verbose_name='Потужність')),
                ('marking_speed', models.CharField(blank=True, max_length=80, verbose_name='Швидкість маркування')),
                ('applications', models.TextField(blank=True, verbose_name='Сфери застосування (кожна з нового рядка)')),
                ('laser_type', models.CharField(blank=True, help_text='Для PDF-брошури з /static/brochures/lasers/', max_length=10, verbose_name='Тип лазера (uv/co2/fiber)')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='brochures/lasers/', verbose_name='PDF-брошура')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='content.contentsection', verbose_name='Розділ')),
            ],
            options={
                'verbose_name': 'Картка розділу',
                'verbose_name_plural': 'Картки розділів',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='LabelingSection',
            fields=[
            ],
            options={
                'verbose_name': 'Розділ (Етикетування)',
                'verbose_name_plural': 'Розділи — Етикетування',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.contentsection',),
        ),
        migrations.CreateModel(
            name='MarkingSection',
            fields=[
            ],
            options={
                'verbose_name': 'Розділ (Маркування)',
                'verbose_name_plural': 'Розділи — Маркування',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.contentsection',),
        ),
        migrations.CreateModel(
            name='QualitySection',
            fields=[
            ],
            options={
                'verbose_name': 'Розділ (Контроль якості)',
                'verbose_name_plural': 'Розділи — КЯ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.contentsection',),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='content.contentsection', verbose_name='Розділ'),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: __import__(
                'src.content.migrations._section_data',
                fromlist=['migrate_legacy_sections'],
            ).migrate_legacy_sections(apps, schema_editor),
            migrations.RunPython.noop,
        ),
    ]
