# Generated by Django 5.1.15 on 2026-06-24 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_content_sections'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='catalog/gallery/', verbose_name='Зображення')),
                ('alt_text', models.CharField(blank=True, max_length=160, verbose_name='Alt-текст')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Додаткове фото',
                'verbose_name_plural': 'Додаткові фото',
                'ordering': ['ordering', 'pk'],
            },
        ),
        migrations.DeleteModel(
            name='LabelingSection',
        ),
        migrations.DeleteModel(
            name='MarkingSection',
        ),
        migrations.DeleteModel(
            name='QualitySection',
        ),
        migrations.AddIndex(
            model_name='productgalleryimage',
            index=models.Index(fields=['content_type', 'object_id'], name='content_pro_content_1bbcd3_idx'),
        ),
    ]
